### ISSUE TITLE
Rename repo to openfisca-ops

### ISSUE THREAD

**Issue by MattiSG** [sgmap/openfisca#6]
Since “openfisca” is an ambiguous name, we usually refer to this repo as “sgmap/openfisca” or “meta-repo”. Former is unpronounceable, latter is unclear to a newcomer.

I used the convention of “-ops” suffices for such repos with great success in the past.

Opinions?

**Comment by laem** [comment]
:+1: sgmap/openfisca was confusing. install-openfisca ? Really straightforward for newcomers.

**Comment by MattiSG** [comment]
No, this does more than installing.

**Comment by MattiSG** [comment]
Done.

Also, [deprecated this repo](https://github.com/sgmap/openfisca/commit/beba011e7da482454f3ac8f219b1d917761cbcbd).
