### ISSUE TITLE
Do we really need openfisca-parsers ?

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/openfisca#7]
Our openfisca server works well without it, was there a reason to reference it here ?

**Comment by MattiSG** [comment]
Yes, it's used for the dynamic generation of the documentation in the `/formula` API, used by Embauche.

**Comment by fpagnoux** [comment]
OK, I confess I should have asked directly before opening an issue :-1: 
Thanks for the quick answer !

**Comment by MattiSG** [comment]
No, that's perfectly fine  :)  Async communication is pretty good.
